package com.example.urlshortener.service;

import com.example.urlshortener.repository.UrlRepository;
import com.google.common.hash.Hashing;
import org.apache.commons.validator.routines.UrlValidator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.nio.charset.StandardCharsets;

@Service
public class UrlShorteningService{

    @Autowired
    UrlRepository repository;

    private static final Logger log = LoggerFactory.getLogger(UrlShorteningService.class);

    public String getShortenedId(String originalUrl){
        UrlValidator urlValidator = new UrlValidator(new String[] {"http", "https"});
        if(urlValidator.isValid(originalUrl)){
            String id = Hashing.murmur3_32().hashString(originalUrl, StandardCharsets.UTF_8).toString();
            log.debug("URL id generated: {}",id);
            repository.setID(id, originalUrl);
            log.debug("URL id={} stored in redis database.",id);
            return id;
        }
        throw new RuntimeException("URL Invalid: " + originalUrl);
    }

    public String getLongUrl(String id){
        log.debug("Id received by service: {}",id);
        String url = repository.fetchUrl(id);
        if(url == null){
            throw new RuntimeException("Error in retrieving url, check your id.");
        }
        log.debug("Url generated by service: {}",url);
        return url;
    }

}